/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/51yqSbJXlhj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"

export function Letterboard() {
  const [text, setText] = useState("")
  const handleClick = (letter) => {
    if (letter === " ") {
      setText((prevText) => prevText + " ")
    } else {
      setText((prevText) => prevText + letter)
    }
  }

  // Add new functions for Backspace and Clear
  const handleBackspace = () => {
    setText((prevText) => prevText.slice(0, -1))
  }

  const handleClear = () => {
    setText("")
  }

  return (
    <div className="flex flex-col items-center justify-center h-screen bg-background">
      <div className="w-full max-w-4xl p-4">
        <div className="bg-card rounded-lg p-4 shadow-lg">
          <textarea
            value={text}
            readOnly
            rows={3}
            className="w-full text-6xl font-bold text-card-foreground bg-transparent resize-none outline-none"
          />
        </div>
      </div>
      <div className="grid grid-cols-7 gap-4 p-4 mt-4">
        {Array.from(Array(26)).map((_, i) => (
          <button
            key={i}
            onClick={() => handleClick(String.fromCharCode(65 + i))}
            className="w-16 h-16 text-4xl font-bold rounded-lg bg-primary text-primary-foreground shadow-md hover:bg-primary/80 transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
          >
            {String.fromCharCode(65 + i)}
          </button>
        ))}
      </div>
      {/* New row for Space, Backspace, and Clear buttons */}
      <div className="flex justify-center gap-4 p-4">
        <button
          onClick={() => handleClick(" ")}
          className="w-32 h-16 text-2xl font-bold rounded-lg bg-primary text-primary-foreground shadow-md hover:bg-primary/80 transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
        >
          Space
        </button>
        <button
          onClick={handleBackspace}
          className="w-32 h-16 text-2xl font-bold rounded-lg bg-primary text-primary-foreground shadow-md hover:bg-primary/80 transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
        >
          Backspace
        </button>
        <button
          onClick={handleClear}
          className="w-32 h-16 text-2xl font-bold rounded-lg bg-primary text-primary-foreground shadow-md hover:bg-primary/80 transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
        >
          Clear
        </button>
      </div>
    </div>
  )
}
